USE "JIRA_HEVO";
CREATE VIEW JIRA_ISSUE_FLAT AS 
SELECT i.*,sc."NAME" AS "STATUS_CATEGORY_NAME",p."NAME" AS "PRIORITY_NAME", r."NAME" AS "RESOLUTION_NAME",
au."DISPLAY_NAME" AS "ASSIGNEE", cu."DISPLAY_NAME" AS "CREATOR", ru."DISPLAY_NAME" AS "REPORTER"
FROM "JIRA_HEVO"."PUBLIC"."JIRA_ISSUE" i 
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_STATUS" s ON i."STATUS_ID" = s."ID" 
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_STATUS_CATEGORY" sc ON s."STATUS_CATEGORY_ID" = sc."ID" 
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_PRIORITY" p ON i."PRIORITY_ID" = p."ID"
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_RESOLUTION" r ON i."RESOLUTION_ID" = r."ID"
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_USER" au ON i."ASSIGNEE_ACCOUNT_ID"=au."ACCOUNT_ID"
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_USER" cu ON i."CREATOR_ACCOUNT_ID"=cu."ACCOUNT_ID"
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_USER" ru ON i."REPORTER_ACCOUNT_ID"=ru."ACCOUNT_ID"

CREATE VIEW JIRA_HEVO.PUBLIC.JIRA_PROJECT_FLAT AS 
SELECT p.*,pc."NAME" AS "PROJECT_CATEGORY_NAME", u."DISPLAY_NAME" AS "LEAD_USER"
FROM "JIRA_HEVO"."PUBLIC"."JIRA_PROJECT" p 
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_PROJECT_CATEGORY" pc ON p."PROJECT_CATEGORY_ID" = pc."ID" 
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_USER" u ON p."LEAD_ACCOUNT_ID"=u."ACCOUNT_ID"



CREATE VIEW JIRA_HEVO.PUBLIC.JIRA_CHANGELOG_FLAT AS 
SELECT cl.*,cld."FIELD",cld."FIELD_ID",cld."FROM" AS "FROM_VALUE",cld."FROM_STRING", 
cld."TO" AS "TO_VALUE", cld."TO_STRING",cld."FIELDTYPE",u."DISPLAY_NAME" AS "AUTHOR" 
FROM "JIRA_HEVO"."PUBLIC"."JIRA_ISSUE_CHANGELOG" cl
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_ISSUE_CHANGE_DETAILS" cld ON cl."ID"=cld."CHANGELOG_ID"
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_USER" u ON cl."AUTHOR_ACCOUNT_ID"=u."ACCOUNT_ID"


CREATE VIEW JIRA_HEVO.PUBLIC.JIRA_LINK_FLAT AS 
SELECT l.*,lt."NAME" AS "LINK_TYPE_NAME", lt."INWARD", lt."OUTWARD",
i."KEY" AS "ISSUE_KEY", li."KEY" AS "LINKED_ISSUE_KEY"
FROM "JIRA_HEVO"."PUBLIC"."JIRA_ISSUE_LINK" l
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_ISSUE_LINK_TYPE" lt
ON l."ISSUE_LINK_TYPE_ID" = lt."ID"
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_ISSUE" i
ON l."ISSUE_ID"=i."ID"
LEFT JOIN "JIRA_HEVO"."PUBLIC"."JIRA_ISSUE" li
ON l."LINKED_ISSUE_ID" = li."ID"


CREATE VIEW JIRA_HEVO.PUBLIC.JIRA_INTERPROJECT_DEPENDANCIES AS
SELECT "LINK_TYPE_NAME","DIRECTION", "ISSUE_ID", "LINKED_ISSUE_ID", I."KEY" AS "ISSUE_KEY", I2."KEY" AS "LINKED_ISSUE_KEY" 
,I."STATUS_CATEGORY_NAME" AS "ISSUE_STATUS_CATEGORY_NAME",I2."STATUS_CATEGORY_NAME" AS "LINKED_ISSUE_STATUS_CATEGORY_NAME"
FROM "JIRA_HEVO"."PUBLIC"."LINK_FLAT" AS IL LEFT JOIN "JIRA_HEVO"."PUBLIC"."ISSUE_FLAT" AS I ON IL."ISSUE_ID"=I."ID"
LEFT JOIN "JIRA_HEVO"."PUBLIC"."ISSUE_FLAT" AS I2 ON IL."LINKED_ISSUE_ID"=I2."ID" 
WHERE "LINK_TYPE_NAME" IN ('Relates','Blocks') AND SPLIT_PART(ISSUE_KEY, '-', 1)!=SPLIT_PART(LINKED_ISSUE_KEY, '-', 1) AND DIRECTION = 'OUTWARD'
AND (I.STATUS_CATEGORY_NAME!='Done' AND I2.STATUS_CATEGORY_NAME!='Done')




--Status change views
CREATE VIEW JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE_INT1" AS
SELECT DISTINCT I."ID" AS "ISSUE_ID", 'Created' AS "From_Status", 'To Do' AS "To_Status",I."CREATED" AS "Start_Date", I."CREATED" AS "End_Date"
  FROM "JIRA_HEVO"."PUBLIC"."ISSUE_FLAT" AS I 
      union 
      -- ... and work our way down one level at a time.
      select ICL2."ISSUE_ID" AS "ISSUE_ID", 
             ICL2."FROM_STRING" AS "From_Status", 
             ICL2."TO_STRING" AS "To_Status", 
             null as "Start_Date", 
             ICL2."CREATED" as "End_Date"
        from "JIRA_HEVO"."PUBLIC"."CHANGELOG_FLAT" AS ICL2 
        WHERE "FIELD"='status'
        order by "ISSUE_ID", "End_Date"

CREATE VIEW JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE_INT2" AS
SELECT ROW_NUMBER() OVER (ORDER BY "ISSUE_ID", "End_Date" ASC) AS "ROW_COUNTER",* from JIRA_HEVO.PUBLIC."ISSUE_STATUS_CHANGE_INT1"

CREATE VIEW JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE_INT3" AS 
SELECT *,ROW_COUNTER-1 AS PREVIOUS_ROW  from JIRA_HEVO.PUBLIC."ISSUE_STATUS_CHANGE_INT2"

/*Fixing the dates on the Created entry*/
CREATE VIEW JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE" AS
SELECT ISC.ROW_COUNTER, ISC.ISSUE_ID,ISC."From_Status" AS "FROM_STATUS", ISC."To_Status" AS "TO_STATUS",ISC."End_Date" AS "END_DATE",ISC2."End_Date" AS "START_DATE" 
FROM JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE_INT3" AS ISC 
LEFT JOIN JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE_INT3" AS ISC2 ON ISC.PREVIOUS_ROW=ISC2.ROW_COUNTER
WHERE "FROM_STATUS" !='Created'
UNION 
SELECT ISC.ROW_COUNTER, ISC.ISSUE_ID,ISC."From_Status" AS "FROM_STATUS", ISC."To_Status" AS "TO_STATUS",ISC."End_Date" AS "END_DATE",ISC."Start_Date" AS "START_DATE" 
FROM JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE_INT3" AS ISC 
LEFT JOIN JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE_INT3" AS ISC2 ON ISC.PREVIOUS_ROW=ISC2.ROW_COUNTER
WHERE "FROM_STATUS" ='Created'
order by "ROW_COUNTER"



--Add the current status views
CREATE VIEW JIRA_HEVO.PUBLIC."JIRA_ISSUE_CURRENT_STATUS" AS
SELECT MAX (ROW_COUNTER) AS ROW_COUNTER,ISSUE_ID, TO_STATUS AS "CURRENT_STATUS",END_DATE AS "DATE_UPDATED" FROM JIRA_HEVO.PUBLIC."JIRA_ISSUE_STATUS_CHANGE" 
GROUP BY ISSUE_ID, TO_STATUS,END_DATE


--Add the Issue Type views
CREATE VIEW JIRA_HEVO.PUBLIC."JIRA_ISSUE_TYPE_CHANGES_INT1" AS
SELECT ICL2."ISSUE_ID" AS "ISSUE_ID", 
             ICL2.FROM_STRING AS "FROM_ISSUE_TYPE", 
             ICL2.TO_STRING AS "TO_ISSUE_TYPE", 
             ICL2.CREATED as "END_DATE",
             ROW_NUMBER() OVER (ORDER BY ICL2.ISSUE_ID, ICL2.CREATED ASC) AS "ROW_COUNTER"
        FROM "JIRA_HEVO"."PUBLIC"."JIRA_CHANGELOG_FLAT" AS ICL2 
        WHERE "FIELD"='issuetype'
        ORDER BY ISSUE_ID, CREATED


CREATE VIEW JIRA_HEVO.PUBLIC."ISSUE_TYPE_CHANGES_INT2" AS
SELECT MAX ("ROW_COUNTER") as "ROW_COUNTER","ISSUE_ID","TO_ISSUE_TYPE" AS "CURRENT_ISSUE_TYPE", "END_DATE" AS "ISSUE_TYPE_DATE_CREATED" 
FROM JIRA_HEVO.PUBLIC."JIRA_ISSUE_TYPE_CHANGES_INT1" GROUP BY ISSUE_ID, "TO_ISSUE_TYPE", "END_DATE"


CREATE VIEW JIRA_HEVO.PUBLIC."ISSUE_TYPE_CHANGES" AS
SELECT -1 AS ROW_COUNTER, ID AS "ISSUE_ID", 'Story' AS "CURRENT_ISSUE_TYPE",CURRENT_TIMESTAMP AS "ISSUE_TYPE_DATE_CREATED" 
FROM "JIRA_HEVO"."PUBLIC"."JIRA_ISSUE_FLAT" WHERE ISSUE_ID NOT IN(SELECT DISTINCT ISSUE_ID FROM "JIRA_HEVO"."PUBLIC"."JIRA_CHANGELOG_FLAT" WHERE "FIELD"='issuetype')
UNION
SELECT * FROM JIRA_HEVO.PUBLIC."JIRA_ISSUE_TYPE_CHANGES_INT2"
